name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  pull_request:
    name: pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.lock') }}
      - name: Install Dependencies
        run: npm install
      - name: Run build
        run: npm run build
      - name: Run lint
        run: npm run lint
      - name: Run test
        run: npm run test
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          wait-on: "http://localhost:8080"
